### ISSUE TITLE
Feature request: toggle Github Actions split window

### ISSUE THREAD

**Issue by utensil** [topaxi/gh-actions.nvim#12]
So far gh-actions.nvim provides command `:GhActions` and a key mapping `<leader>+gh`, which is nice. But it seems that I have to focus the split window then `:q` to close it. Similar plugins will provide a toggle command to turn it on and off, and use the same key mapping.

Is this a desirable feature to implement? 😄

**Comment by topaxi** [comment]
Seems like this would be a common pattern and desired feature, yes!

I'd be open for a PR which implements this with an explicit vim command.

One of these two ways I'd gladly accept:
- Add a new `GhActionsClose` or `GhActionsToggle` command
- Extend the existing `GhActions` command to accept subcommands like `open`, `close`, `toggle`

In the meantime, if you use lazy, you should be able to implement this in your plugin spec like this:

```lua
{
  'topaxi/gh-actions.nvim',
  keys = {
    { '<leader>gh', '<cmd>GhActions<cr>', desc = 'Open Github Actions' },
    { '<leader>gc', function() require('gh-actions').close() end, desc = 'Close Github Actions' },
  },
  opts = {},
},

```

**Comment by utensil** [comment]
Ah, nice! I didn't realize how to get the window (i.e. `require('gh-actions')`) for closing.

**Comment by topaxi** [comment]
I added subcommands to the `GhActions` command to toggle/open/close.

See the [README](https://github.com/topaxi/gh-actions.nvim?tab=readme-ov-file#commands) for usage.
