### ISSUE TITLE
Support for GitHub Enterprise Server?

### ISSUE THREAD

**Issue by brianphillips** [topaxi/gh-actions.nvim#4]
Hello - we use GitHub Enterprise Server and I'm wondering if you would be open to adding support (or accepting a PR) that makes the base URL for the API dynamic based on auto-detection of the repository's origin URL (similar to how the `gh` CLI tool works across both public github.com and internal github.my-company.com GHES instance).

**Comment by topaxi** [comment]
I'd be open for a PR, I don't have access to any github enterprise instance to test anything though :grin:
