### ISSUE TITLE
curl: (6) Could not resolve host: nil

### ISSUE THREAD

**Issue by gmankab** [topaxi/gh-actions.nvim#8]
```log
Error executing luv callback:
....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:300: get https://nil/api/v3/repos/nil/actions/runs - curl error exit_code=6 s
tderr={ "curl: (6) Could not resolve host: nil" }
stack traceback:
        [C]: in function 'error'
        ....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:300: in function '_user_on_exit'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:241: in function '_shutdown'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:48: in function <.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/
job.lua:39>
Press ENTER or type command to continue
```

**Comment by topaxi** [comment]
What is the output of running `git config --get remote.origin.url` in the affected repository? :)

**Comment by gmankab** [comment]
i can't check it for next few days, but i think you're right that the problem is in remote url

can you please implement user friendly error message for this case?

feel free to close issue

**Comment by topaxi** [comment]
A user friendly error message would be welcome, but as I'm working on this in my free time and it's not a big issue to myself, I'll leave it as is for now.

I'd be happy to accept a PR which improves error reporting on this or in general :)

Thank you for reporting this issue.
