### ISSUE TITLE
Input-Validation seems to raise error

### ISSUE THREAD

**Issue by kronn** [topaxi/gh-actions.nvim#9]
I had a wonderful encounter this morning. Well, "wonderful". I noticed a failed build in one project and wanted to check. Naturally, I wanted to do this from inside NeoVim (10.1). The swift input of my trigger triggered this message in bright red:

```
Error executing vim.schedule lua callback: ...kickstart/lazy/gh-actions.nvim/lua/gh-actions/github.lua:74: opt: expected table, got string
stack traceback:                                                                   
        [C]: in function 'error'                                                   
        vim/shared.lua: in function 'validate'                                     
        ...kickstart/lazy/gh-actions.nvim/lua/gh-actions/github.lua:74: in function 'get_workflows'                                                                   
        ...m-kickstart/lazy/gh-actions.nvim/lua/gh-actions/init.lua:38: in function ''                                                                                
        vim/_editor.lua: in function <vim/_editor.lua:0>  
```

Color-choices aside, I wasn't happy. Even more so, since line 74 seems to expect a string.

https://github.com/topaxi/gh-actions.nvim/blob/2fce4e35116f44f6f00dbb067516403a93bf8208/lua/gh-actions/github.lua#L74-L76

I did what many do and disabled the validations, and then it worked. Most likely, it is now broken elsewhere. Assuming you know more about this plugin than I do: what information would you need to debug this properly? How can I debug this?

My personal path to paradise can involve both a local config fix and a patch in a pull-request. Or one of those. 

ICANHAZ HALP PLZ? KTHXBAI.

**Comment by topaxi** [comment]
I've basically added this validation to maybe get a better stack trace due to the error reported in #8.

I think the validations are unhappy as nightly neovim changed the function signature of `vim.validate` to a more performant default while stable releases expect a table instead of multiple arguments.

Thanks for reporting! Hope you are doing well my friend :hugs: 

Fixed in 74d624edfe3ef6538396987316675a5e6d319ecb
